// Generates a PostgreSQL DDL "baseline" from the EF Core model snapshot so the ported
// SQL scripts (Sql/Accounting/*.sql) can be tested against the real Xorva schema
// without a .NET SDK. Tables/columns/PKs/indexes only — enough for the scripts and
// tests; no FKs (EF creates them, but the scripts never depend on them).
//
//   node snapshot2sql.mjs > baseline.sql
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const src = fs.readFileSync(path.join(here, '../../Migrations/XorvaDbContextModelSnapshot.cs'), 'utf8');

const entities = [];
const entityRe = /modelBuilder\.Entity\("([^"]+)", b =>\s*\{([\s\S]*?)\n {16}\}\);/g;
let m;
while ((m = entityRe.exec(src))) {
  const [, clr, body] = m;
  const table = /b\.ToTable\("([^"]+)"/.exec(body)?.[1];
  if (!table) continue;                        // owned types / relationship blocks
  const cols = [];
  const propRe = /b\.(?:Property|PrimitiveCollection)<((?:[^<>]|<[^<>]*>)+)>\("([^"]+)"\)((?:\s*\.[A-Za-z]+\([^;]*?\))*);/g;
  let p;
  while ((p = propRe.exec(body))) {
    const [, clrType, name, mods] = p;
    const type = /\.HasColumnType\("([^"]+)"\)/.exec(mods)?.[1] ?? 'text';
    const required = /\.IsRequired\(\)/.test(mods) || !clrType.endsWith('?') && !['string', 'byte[]'].includes(clrType) && !clrType.startsWith('List<');
    const def = /\.HasDefaultValue\(([^)]*)\)/.exec(mods)?.[1];
    let defSql = '';
    if (def !== undefined) defSql = ` DEFAULT ${def.startsWith('"') ? `'${def.slice(1, -1)}'` : def}`;
    cols.push(`  "${name}" ${type}${required ? ' NOT NULL' : ''}${defSql}`);
  }
  const pk = /b\.HasKey\(([^)]+)\)/.exec(body)?.[1].replace(/"/g, '"').split(',').map(s => s.trim()).join(', ');
  const checks = [...body.matchAll(/t\.HasCheckConstraint\("([^"]+)", "((?:[^"\\]|\\.)*)"\)/g)]
    .map(c => `  CONSTRAINT "${c[1]}" CHECK (${c[2].replace(/\\"/g, '"')})`);
  const indexes = [...body.matchAll(/b\.HasIndex\(([^)]+)\)([\s\S]*?);/g)].map(ix => {
    const cols = ix[1].split(',').map(s => s.trim().replace(/"/g, '"'));
    const unique = /\.IsUnique\(\)/.test(ix[2]);
    const name = /\.HasDatabaseName\("([^"]+)"\)/.exec(ix[2])?.[1] ?? `IX_${table}_${cols.map(c => c.replace(/"/g, '')).join('_')}`;
    return `CREATE ${unique ? 'UNIQUE ' : ''}INDEX "${name}" ON "${table}" (${cols.join(', ')});`;
  });
  entities.push({ table, cols, pk, checks, indexes });
}

let out = '-- Generated by Sql/Tests/snapshot2sql.mjs from XorvaDbContextModelSnapshot.cs\n';
for (const e of entities) {
  const parts = [...e.cols];
  if (e.pk) parts.push(`  CONSTRAINT "PK_${e.table}" PRIMARY KEY (${e.pk})`);
  parts.push(...e.checks);
  out += `CREATE TABLE "${e.table}" (\n${parts.join(',\n')}\n);\n`;
  out += e.indexes.join('\n') + (e.indexes.length ? '\n' : '');
}
process.stdout.write(out);
